[env:nodemcu-32s]
platform = espressif32@6.9.0
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB


build_flags =
    -I src
    -D LV_CONF_INCLUDE_SIMPLE
    -D CONFIG_BT_NIMBLE_ENABLED=0
    -D ARDUINOJSON_ENABLE_ARDUINO_STRING=0

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson@^7.4.2
    mikalhart/TinyGPSPlus@^1.1.0